spring:
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/aabouraya/config-repository.git"
          clone-on-start: true
          search-paths: "config/{application}"
server:
  port: 8888

logging:
  level:
    org:
      springframework: trace
eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka/"
